// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZRk9-o9S89ejqx5AGlj8bq4wRdQKqW4',
    appId: '1:58514067855:web:2626cb9b8a10abd268bbfa',
    messagingSenderId: '58514067855',
    projectId: 'color-notes-9ab85',
    authDomain: 'color-notes-9ab85.firebaseapp.com',
    storageBucket: 'color-notes-9ab85.appspot.com',
    measurementId: 'G-HX45JSX6FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAYnakXp6snMRbAKiSxu51J3BmA5SaBc',
    appId: '1:58514067855:android:ff32335c42b8c90468bbfa',
    messagingSenderId: '58514067855',
    projectId: 'color-notes-9ab85',
    storageBucket: 'color-notes-9ab85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtebOjMe_LhHqV-PDq1dJEjLeVUvB0gA',
    appId: '1:58514067855:ios:759d610a1206276268bbfa',
    messagingSenderId: '58514067855',
    projectId: 'color-notes-9ab85',
    storageBucket: 'color-notes-9ab85.appspot.com',
    androidClientId: '58514067855-fm24qtnpe4m1jhrr7g54t23g02bsoet7.apps.googleusercontent.com',
    iosClientId: '58514067855-olis2pm22tqi4kkjljrnmsu3sb5v9sap.apps.googleusercontent.com',
    iosBundleId: 'com.example.colorNotes',
  );
}
